### PR TITLE
update slack channel in readme

### PR DESCRIPTION
**Pull request by Benjamintf1**

### CODE REVIEW

**Review by MarcPaquette — APPROVED** [review]

**Comment by MarcPaquette** [comment]
Changes look good to me.

**Comment by dsabeti** [comment]
@Benjamintf1 It looks like this change was forked from a commit that was broken -- hence the failing tests. Can you merge `develop` (or rebase your branch on top of it and force push) to get the tests green?

**Comment by Benjamintf1** [comment]
rebased.

**Comment by Benjamintf1** [comment]
Should I rebase again?

**Review by winkingturtle-vmw — APPROVED** [review]

**Pull request merged**
